# Generated by Django 4.0 on 2023-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_paymenymodel_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartmodel',
            unique_together={('user', 'product')},
        ),
        migrations.AlterIndexTogether(
            name='cartmodel',
            index_together={('user', 'product')},
        ),
    ]
